# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "todo" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"text" VARCHAR NOT NULL,"created_on" TIMESTAMP NOT NULL,"completed_on" TIMESTAMP);

# --- !Downs

drop table "todo";

